### ISSUE TITLE
MozDef worker redesign proposal

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1096]
# MozDef work redesign

## Background

The current logic is

* Each worker has pre-logic which detects, based on the payload, what source the event came from and modifies the event to set "customendpoint" to true for some events
* For events which either do not arrive with "customendpoint" set to true or which are not pre-transformed to have "customeendpoint" set to true, the event is passed through the "keyMapping" function ([Background on the name customendpoint](https://github.com/mozilla/MozDef/blob/2d7d3fdead27c6e716b7cfceb9b2a164456c24e2/loginput/index.py#L112) )
* keyMapping
  * sets event fields mozdefhostname and receivedtimestamp
  * moves the payload fields around when it detects that the source is heka
  * converts charactersets on payload and summary
  * converts timestamps
  * converts fields with various names into single common names like severity, facility, processid, eventsource, category
  * handles cases where the details field or fields field is not a dictionary
  * transform fields like details.foo_int to details['foo'] and set the type to 'int'
  * detects if nxlog is the source of the event by the presense of the keys 'Domain' and 'SourceModuleType' and if so dumps all fields into details
  * sets utctimestamp if it wasn't in the event
* All events are then sent through the plugin system
  * the event is sent to each plugin serially
  * each plugin determines if the event matches criteria indicating that plugins transformation should be applied
  * many of those criteria are fuzzy for example, flattening the entire event object structure and looking through all keys for the presense of a matching word
  * for plugins that do match they transform fields
  * plugins can optionally abort further plugin processing and drop the message entirely
* for any required fields that are missing from the event, set them to the value "UNKNOWN" or default values like datetime.now() or the current hostname
* set the ES doc_type to either
  * the value of the _type field in the event if present
  * cef if 
    * the field "endpoint" is set to "cef" OR if the field "fields" or "details" contains the keys devicevendor, deviceproduct and deviceversion
  * event otherwise
* set the ES body to either
  * the value of the _source field in the event if present
  * the event otherwise
* save the event to ES in the 'events' index

What data producers natively set the customendpoint field? Bro, Nubis

There are two types of data producers, ones which are aware of Mozdef and ones which are not.

# Proposal

* Establish 3 workers, sqs, papertrail and amqp(eventtask) which exclusively fetch inbound events but do no transformations
* Once the worker obtains the event, it calls the categorization tier
* Create a new "categorize" tier which observes the inbound event to determine it's category
  * This would replace the current plugin based categorization process which is fuzzy and allows a message to trigger multiple plugins
  * Categorization would follow an ordered sequence of tests and when the first test returns true, the category is defined and no further categorizations are executed
  * An event can have only one category
  * Categorization logic could be contained in a dedicated function in each plugin
  * The logic must not be broad, and take care to only match on the desired events
* Once the event category is defined, the worker calls the event transformation tier
  * Each category has a single transformation function
  * For some categories where we really don't understand anything about the data producer that transformation would use a library "keyMapping" function if it was appropriate
  * For most categories, we would not employ optimistic fuzzy data transformations but instead use intentional per-category data transformations based on the type of data that data producer creates
  * An acceptable data transformation for a given category's transformation to apply is to drop the event
  * Each transformation would use a library based set of default values in the case where required fields are missing.
    * Ideally for most transformation tiers, any event which unexpectedly is missing a field and uses a default should trigger an error/alert/log so someone in infosec can look into why we're receiving data in an unexpected format
  * No transformation logic is contained outside the transformation tier so that *all* transformation behaviour can potentially be set for a given categories transformation plugin

What does this accomplish

* seperate plugin filter logic from transformation logic for clarity and ease of development
* move to model where only a single plugin category can apply for a simpler to understand outcome for a given message
* all transformation logic is found in one place instead of across the worker and the plugins for an easier to understand outcome for a given message
* all transformation logic is removed from workers to make transport swappable and distinct from payload transformation for clarity and ease of maintenance
* move common transformation steps into libraries used in plugins instead of hard coded into workers for clarity and to allow for transformations which do not require these common transformation steps
* allow for a gradual move to the new model by cutting over data producers one at a time to the new worker which would use the new plugins. This way to move a single data producer over only requires building the new worker for that transport method and the single plugin that matches that data producers data

## Pseudo code

Here are some blocks of psuedo code illustrating some of the ideas in the proposal

worker_sqs.py

```python
while True;
  client = boto3.client('sqs')
  response = client.receive_message()['Messages']
  messages = [standardize_event(x) for x in response]  # This merely puts the event in roughly the same structure as what the other workers would recieve so that plugins can handle them, disregarding what worker delviered them. This does not include any content specific transformation, only standardizing the differences between the structure of data arriving via amqp vs sqs for example
  for message in messages:
    for plugin in plugin_map:
      if 'is_matching' in dir(plugin_map[plugin]) and 'transform' in dir(plugin_map[plugin]):
        # plugin conforms to the new style of plugins and has an is_matching method
        if plugin_map[plugin].is_matching(message):
          event = plugin_map[plugin].transform(message)
          esConnection.save_event(event)
          break  # Finish iterating through plugins and move on to the next message
```

nubis_plugin.py
```python
def is_matching(message):
  return message['sender'] == 'nubis'

def transform(message)
  message['body']['details']['sourceport'] = 'foo'
  return message
```

**Comment by mpurzynski** [comment]
Thanks for reporting a very interesting software design problem. I'd like to clarify some claims here, as the description is not very accurate.

> for any required fields that are missing from the event, set them to the value "UNKNOWN" or default values like datetime.now() or the current hostname

The UNKNOWN value is set by either plugins or the generic code to help with data sources like cloudtrail, that do not follow any logic, pattern or definition and have fields that either show-up or vanish. Unfortunately, for some data sources (like cloudtrail) a field a.b can be there on day 1 and be gone (for the same event) on day 2 and appear again, as a differrent type, on day 3. And then go away completely.
This creates problems with "vanishing fields" during the IR or alerts writing.

The current hostname is set for the mozdefhostname field, according to the standard.
The datetime.now() is stored in the receivedtimestamp field.

> Establish 3 workers, sqs, papertrail and amqp(eventtask) which exclusively fetch inbound events but do no transformations

There is no way 3 workers can handle the load of events that we have. Did you mean three worker types or classes?

> This would replace the current plugin based categorization process which is fuzzy and allows a message to trigger multiple plugins

The current process is fuzzy on purpose and it is by design that a single message can be acted upon by multiple plugins.

To show why this is useful, let me give you two examples

- The ipfixup.py plugin seeks for anything that might be an IP address, in multiple places, and when it finds it, does some standarization and moves data around (like moving the IP from the cluster_client_ip to the sourceipaddress field, among others)
- the geoip plugin acts on data produced by the ipfixup plugin and attaches intels about geolocation
The benefit here is that if a source ABC starts sending an IP address, or moves it around, we get the Geo intel "for free" - without constant monitoring of every data source and missing crucial data in the time period between the source change and us pushing the fix to production.

I will not comment on the design proposed, but will ask a different question instead - *why*?

The design proposed means basically rewriting most of MozDef's code from scratch. That takes people and time away from real-world problems and it creates a project that might be interesting from the computer-science studies point of view, without benefiting us much.

I do not see the value proposition here.

**Comment by gene1wood** [comment]
> Did you mean three worker types or classes?

Yes, 3 `.py` files which would manifest whatever number of running workers that is needed for load.
