### ISSUE TITLE
File ownership in docker containers allows mozdef user to modify code

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1374]
Many of the docker containers have code which sets files to be owned by the `mozdef` user. An effect of this combined with the umask used granting owners write permissions results in cases where the running process has rights to modify the code in the container. If an attacker found a vulnerability in one of the MozDef listeners this would allow them to modify what the container did.

What's the original reason for setting the `mozdef` user as the owner of much of the code? Could we get away with identifying the subset of files which the `mozdef` user needs rights to write to and leaving all remaining files (including the codebase and config files) owned by root?

I wanted to pose this question since there very well may be a good reason for the file ownership working this way and I wanted to find out before PRing a change.

**Comment by pwnbus** [comment]
I can think of a few situations where the process running, needs write access
1. Pip install writes to /opt/mozdef/envs/python/
2. When building meteor, since it writes to /opt/mozdef/envs/meteor
3. The alerts process writes /opt/mozdef/envs/mozdef/alerts/celerybeat-schedule.db
4. Cron container writes to /opt/mozdef/envs/mozdef/data (this is a shared volume)

I'd say if we could get away with tightening the overall perms, let's do it!

I'd say there maybe are a few others

**Comment by Phrozyn** [comment]
Mozdef runs nginx/openresty as mozdef.
However meteor can run as root, but I prefer not running processes as root.

If anything we could review and look at running processes not required to
be written to or executed by mozdef as a different unprivileged user rather
than privileged one.

This will add complexity, and I think we should step back and evaluate the
possibilities and risk level before launching into this.

I think there are other areas worth tackling such as protecting the
elasticsearch api endpoint.

Mozdef can only write to itself. It is not a privileged user.

If a system is compromised on the OS level the docker instances can be
considered compromised.

Any user the filesystem is owned by could be compromised as well. Mozdef
being accessed via proxy shouldn't allow direct access to any ports not
configured via the proxy.

I somewhat feel this is ends up creating circular dependencies. Where we
are simply adding complexity and gaining little value.

**Comment by gene1wood** [comment]
> If a system is compromised on the OS level the docker instances can be
considered compromised.

Right, I'm talking about compromise of a process running within a container, not on the host OS

> I somewhat feel this is ends up creating circular dependencies

Can you give more details on this?

**Comment by gdestuynder** [comment]
Chiming in by request - the following is my general advice and what is considered standard practice, although of course I don't have full context on how MozDef currently does this.

> Mozdef runs nginx/openresty as mozdef.
> However meteor can run as root, but I prefer not running processes as root.

Generally you would do the opposite, i.e. files owned by `root` and process running as `mozdef`. This ensures that the process(es) running as `mozdef` cannot modify code or other files. Ideally each daemon type run as its own user (or/and role if using SELinux or similar) and owns certain files as writable where necessary, while other files that are read-only are usually owned by `root`.

>  Pip install writes to /opt/mozdef/envs/python/
>  When building meteor, since it writes to /opt/mozdef/envs/meteor

The build/install process should run separately from the running code regardless, these may run as `root` or another user that is privileged, as long as you don't trigger them from MozDef itself :)

> The alerts process writes /opt/mozdef/envs/mozdef/alerts/celerybeat-schedule.db
>  Cron container writes to /opt/mozdef/envs/mozdef/data (this is a shared volume)

These would be running as `mozdef` writing to files owned by `mozdef` in these directory like right now. Ideally you could have separate users for them, but in the spiriting of iteration, they could be left as is for now. The more of these you identify the better though, because it means these are files you wouldn't change to "root owned".

Hope this helps!
