### ISSUE TITLE
taskConsumer class doesn't extend kombu.mixins.ConsumerMixin

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#392]
Currently the [`taskConsumer` class](https://github.com/mozilla/MozDef/blob/1dd036d22f8cc425a93a59bfa849e152048a67e7/mq/esworker.sqs.py#L265) in [`esworker.sqs.py`](https://github.com/mozilla/MozDef/blob/1dd036d22f8cc425a93a59bfa849e152048a67e7/mq/esworker.sqs.py) extends the [`object`](https://docs.python.org/2/library/functions.html#object) built in class.

Since this class appears to be based on the [`kombu messaging library`](http://docs.celeryproject.org/projects/kombu/en/latest/introduction.html) why doesn't `taskConsumer` extend [`kombu.mixins.ConsumerMixin`](http://docs.celeryproject.org/projects/kombu/en/latest/reference/kombu.mixins.html)?

**Comment by jeffbryner** [comment]
The kombu object didn't play well with the SQS queue. I don't remember specifically what the issue was, (I think it was around base64 encoding) but I couldn't get it to work using the underlying kombu library. So this allows us to work around that, keeping the same basic structure without solving kombu issues.
