### ISSUE TITLE
Where is the docker container ?

### ISSUE THREAD

**Issue by neomh** [mozilla/MozDef#616]
Hello

I can't seem to find one. Did you remove it ?

**Comment by pwnbus** [comment]
@neomh We currently aren't publishing the docker container to dockerhub or any external registry. 

We've created a few make commands that can help in building and starting MozDef in docker, but that requires ~10 minutes to build and you gotta pull mozdef down via source in order to do that (which I understand is not ideal). See https://mozdef.readthedocs.io/en/latest/installation.html#docker for more details.

I'm gonna close this issue, since I've created https://github.com/mozilla/MozDef/issues/617 to keep track of the work to actually do the work.
