### ISSUE TITLE
proxy_drop.py

### ISSUE THREAD

**Issue by Phrozyn** [mozilla/MozDef#668]
#### ISSUE TYPE
 - Bug Report

#### COMPONENT NAME
proxy_drop.py

#### DESCRIPTION
proxy_drop.py currently is broken as in it's current configuration it would fire on every proxy event. There is no significant term to search on for specifically dropped events.

We should work on targeting the specific events we want to alert on, rather than all events.
In this case, those events would be dropped events.

**Comment by claudijd** [comment]
FWIW, there is a specific term, and this is:

Key: details.proxyaction
Value: TCP_DENIED/-

That said, I agree that deny only is not enough to alert, this is why we're adding these alerts instead, which will present more IR value than deny events alone, which represent mostly misconfigs rather than malicious behavior.

https://github.com/mozilla/MozDef/pull/748
https://github.com/mozilla/MozDef/pull/750
